# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 05:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('is_first', models.BooleanField(default=True)),
                ('is_last', models.BooleanField(default=True)),
                ('step_no', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ussd_page',
            },
        ),
        migrations.CreateModel(
            name='USSDProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('service_provider', models.IntegerField(choices=[(1, "Africa's Talking")], null=True)),
                ('service_code', models.CharField(max_length=100)),
                ('is_sandbox', models.NullBooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ussd_provider',
            },
        ),
        migrations.CreateModel(
            name='USSDRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('request_closed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_requests', to='ussd.USSDPage')),
                ('previous_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_requests', to='ussd.USSDPage')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussd.USSDProvider')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ussd_request',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ussdrequest',
            unique_together=set([('session_id', 'user')]),
        ),
    ]
